conexao

diff --git a/SSHPLUS/modulos/conexao b/SSHPLUS/modulos/conexao
--- a/SSHPLUS/modulos/conexao
+++ b/SSHPLUS/modulos/conexao
@@ -2,10 +2,11 @@
 #====================================================
 #	SCRIPT: CONEXAO SSHPLUS MANAGER
 #	DESENVOLVIDO POR:	CRAZY_VPN
+#	DATA ATUALIZACAO:	28 DEZ 2020 
 #	CONTATO TELEGRAM:	http://t.me/crazy_vpn
 #	CANAL TELEGRAM:	http://t.me/sshplus
 #====================================================
-[[ $(awk -F" " '{print $2}' /usr/lib/licence) == "@crazy_vpn" ]] && {
+[[ $(awk -F" " '{print $2}' /usr/lib/licence) == "@CRAZY_VPN" ]] && {
 	ram1=$(free -h | grep -i mem | awk {'print $2'})
 	ram2=$(free -h | grep -i mem | awk {'print $4'})
 	ram3=$(free -h | grep -i mem | awk {'print $3'})
@@ -71,6 +72,7 @@
 						apt-get remove squid3 -y >/dev/null 2>&1
 						apt-get purge squid3 -y >/dev/null 2>&1
 						rm -rf /etc/squid3 >/dev/null 2>&1
+						apt autoremove -y >/dev/null 2>&1
 					}
 				}
 				fun_bar 'rem_sqd'
@@ -97,7 +99,7 @@
 				read -p "Digite seu IP: " IP
 			}
 			echo -e "\n\033[1;33mQUAIS PORTAS DESEJA ULTILIZAR NO SQUID \033[1;31m?"
-			echo -e "\n\033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mDEFINA AS PORTAS EM SEQUENCIA \033[1;33mEX: \033[1;37m80 8080 8799"
+			echo -e "\n\033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mDEFINA AS PORTAS EM SEQUENCIA \033[1;33mEX: \033[1;37m80 8080"
 			echo ""
 			echo -ne "\033[1;32mINFORME AS PORTAS\033[1;37m: "
 			read portass
@@ -109,9 +111,27 @@
 			for porta in $(echo -e $portass); do
 				verif_ptrs $porta
 			done
-			echo -e "\n\033[1;32mINSTALANDO SQUID PROXY\033[0m"
-			echo ""
-			fun_bar 'apt-get update -y' 'apt-get install squid3 -y'
+			[[ $(grep -wc '14' /etc/issue.net) != '0' ]] || [[ $(grep -wc '8' /etc/issue.net) != '0' ]] && {
+				echo -e "\n\033[1;32mINSTALANDO SQUID PROXY\033[0m\n"
+				fun_bar 'apt update -y' "apt install squid3 -y"
+			} || {
+				echo -e "\n\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mSQUID VERSAO 3.3.X\n\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mSQUID VERSAO 3.5.X\033[0m\n"
+				read -p "$(echo -e "\033[1;32mINFORME UMA OPÇÃO \033[1;37m: ")" -e -i 1 opc
+				[[ -z "$opc" ]] && {
+					echo -e "\n\033[1;31mOpcao invalida!"
+					sleep 2
+					fun_conexao
+				}
+				[[ "$opc" != '1' ]] && {
+					[[ "$opc" != '2' ]] && {
+						echo -e "\n\033[1;31mOpcao invalida !"
+						sleep 2
+						fun_conexao
+					}
+				}
+				echo -e "\n\033[1;32mINSTALANDO SQUID PROXY\033[0m\n"
+				fun_bar 'apt update -y' "instsqd $opc"
+			}
 			if [[ -d "/etc/squid/" ]]; then
 				var_sqd="/etc/squid/squid.conf"
 				var_pay="/etc/squid/payload.txt"
@@ -119,60 +139,61 @@
 				var_sqd="/etc/squid3/squid.conf"
 				var_pay="/etc/squid3/payload.txt"
 			else
-				echo -e "\n\033[1;31mERRO ! SQUID PROXY CORROMPEU\033[0m"
+				echo -e "\n\033[1;33m[\033[1;31mERRO\033[1;33m]\033[1;37m: \033[1;33mO SQUID PROXY CORROMPEU\033[0m"
 				sleep 2
 				fun_conexao
 			fi
-			echo ".claro.com.br/
-.claro.com.sv/
-.facebook.net/
-.netclaro.com.br/
-.speedtest.net/
-.tim.com.br/
-.vivo.com.br/
-.oi.com.br/" >$var_pay
-			echo "acl url1 dstdomain -i 127.0.0.1
-acl url2 dstdomain -i localhost
-acl url3 dstdomain -i $ipdovps
-acl url4 dstdomain -i /SSHPLUS?
-acl payload url_regex -i "$var_pay"
-acl all src 0.0.0.0/0
-http_access allow url1
-http_access allow url2
-http_access allow url3
-http_access allow url4
-http_access allow payload
-http_access deny all
- 
-#Portas" >$var_sqd
+			cat <<-EOF >$var_pay
+				.whatsapp.net/
+				.facebook.net/
+				.twitter.com/
+				.speedtest.net/
+			EOF
+			cat <<-EOF >$var_sqd
+				acl url1 dstdomain -i 127.0.0.1
+				acl url2 dstdomain -i localhost
+				acl url3 dstdomain -i $ipdovps
+				acl url4 dstdomain -i /SSHPLUS?
+				acl payload url_regex -i "$var_pay"
+				acl all src 0.0.0.0/0
+
+				http_access allow url1
+				http_access allow url2
+				http_access allow url3
+				http_access allow url4
+				http_access allow payload
+				http_access deny all
+				 
+				#Portas
+			EOF
 			for Pts in $(echo -e $portass); do
 				echo -e "http_port $Pts" >>$var_sqd
 				[[ -f "/usr/sbin/ufw" ]] && ufw allow $Pts/tcp
 			done
-			echo -e "
-#Nome squid
-visible_hostname SSHPLUS 
-via off
-forwarded_for off
-pipeline_prefetch off" >>$var_sqd
+			cat <<-EOF >>$var_sqd
+				#Nome squid
+				visible_hostname SSHPLUS 
+				via off
+				forwarded_for off
+				pipeline_prefetch off
+			EOF
 			sqd_conf() {
 				[[ -d "/etc/squid/" ]] && {
-					squid -k reconfigure
 					service ssh restart
+					/etc/init.d/squid restart
 					service squid restart
-				} || {
-					[[ -d "/etc/squid3/" ]] && {
-						squid3 -k reconfigure
-						service ssh restart
-						service squid3 restart
-					}
+				}
+				[[ -d "/etc/squid3/" ]] && {
+					service ssh restart
+					/etc/init.d/squid3 restart
+					service squid3 restart
 				}
 			}
 			echo -e "\n\033[1;32mCONFIGURANDO SQUID PROXY\033[0m"
 			echo ""
 			fun_bar 'sqd_conf'
 			echo -e "\n\033[1;32mSQUID INSTALADO COM SUCESSO!\033[0m"
-			sleep 3.5s
+			sleep 2.5s
 			fun_conexao
 		fi
 	}
@@ -535,18 +556,18 @@ pipeline_prefetch off" >>$var_sqd
 					#crt='EC'
 					#openssl genrsa -out key.pem 2048 >/dev/null 2>&1
 					#(
-						#echo $crt
-						#echo $crt
-						#echo $crt
-						#echo $crt
-						#echo $crt
-						#echo $crt
-						#echo $crt
+					#echo $crt
+					#echo $crt
+					#echo $crt
+					#echo $crt
+					#echo $crt
+					#echo $crt
+					#echo $crt
 					#) | openssl req -new -x509 -key key.pem -out cert.pem -days 1050 >/dev/null 2>&1
 					#cat cert.pem key.pem >>/etc/stunnel/stunnel.pem
 					#rm key.pem cert.pem >/dev/null 2>&1
 					sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/stunnel4
-					cd /etc/stunnel && wget sshplus.xyz/script/stunnel.pem && cd $HOME
+					cd /etc/stunnel && wget https://raw.githubusercontent.com/AAAAAEXQOSyIpN2JZ0ehUQ/SSHPLUS-MANAGER-FREE/master/Install/stunnel.pem && cd $HOME
 				}
 				fun_bar 'ssl_certif'
 				echo -e "\n\033[1;32mINICIANDO O SSL TUNNEL !\033[0m"
@@ -981,7 +1002,6 @@ pipeline_prefetch off" >>$var_sqd
 			clear
 			echo -e "\E[44;1;37m              INSTALADOR OPENVPN               \E[0m"
 			echo ""
-			# OpenVPN instalador e criação do primeiro usuario
 			echo -e "\033[1;33mRESPONDA AS QUESTOES PARA INICIAR A INSTALACAO"
 			echo ""
 			echo -ne "\033[1;32mPARA CONTINUAR CONFIRME SEU IP: \033[1;37m"
@@ -1206,8 +1226,8 @@ exit 0' >$RCLOCAL
 				sndbuf 0
 				rcvbuf 0
 				remote /SSHPLUS? $porta
-				#payload "HTTP/1.0 [crlf]Host: m.youtube.com[crlf]CONNECT HTTP/1.0[crlf][crlf]|[crlf]"
-				http-proxy $IP 8080
+				#payload "CONNECT 127.0.0.1:1194[split][crlf] HTTP/1.0 [crlf][crlf]#"
+				http-proxy $IP 80
 				resolv-retry 5
 				nobind
 				persist-key
